# -*- coding: utf-8 -*-
"""final_mcq_gen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-wuz_CJrOFx3AHW4jWoXUW6CDh_0GdZ
"""

import spacy
import random
from collections import Counter

text = """
The Greek historian knew what he was talking about. The Nile River fed Egyptian civilization for hundreds of years.
The Longest River the Nile is 4,160 miles long—the world’s longest river. It begins near the equator in Africa and
flows north to the Mediterranean Sea. In the south the Nile churns with cataracts. A cataract is a waterfall. Near the
sea the Nile branches into a delta. A delta is an area near a river’s mouth where the water deposits fine soil called silt.
In the delta, the Nile divides into many streams. The river is called the upper Nile in the south and the lower Nile in the
north. For centuries, heavy rains in Ethiopia caused the Nile to flood every summer. The floods deposited rich soil along the
Nile’s shores. This soil was fertile, which means it was good for growing crops. Unlike the Tigris and Euphrates,
the Nile River flooded at the same time every year, so farmers could predict when to plant their crops.
"""

num_questions = 10

nlp = spacy.load('en_core_web_sm')
# Process the text with spaCy
doc = nlp(text)

# Extract sentences from the text
sentences = [sent.text for sent in doc.sents]

# Randomly select sentences to form questions
selected_sentences = random.sample(sentences, min(num_questions, len(sentences)))

import spacy
from collections import Counter
import random

# Load English tokenizer, tagger, parser, NER, and word vectors
nlp = spacy.load("en_core_web_sm")

def generate_mcqs(text, num_questions=10):
    # Process the text with spaCy
    doc = nlp(text)

    # Extract sentences from the text
    sentences = [sent.text for sent in doc.sents]

    # Randomly select sentences to form questions
    selected_sentences = random.sample(sentences, min(num_questions, len(sentences)))

    # Initialize list to store generated MCQs
    mcqs = []

    # Generate MCQs for each selected sentence
    for sentence in selected_sentences:
        # Process the sentence with spaCy
        sent_doc = nlp(sentence)

        # Extract entities (nouns) from the sentence
        nouns = [token.text for token in sent_doc if token.pos_ == "NOUN"]

        # Ensure there are enough nouns to generate MCQs
        if len(nouns) < 2:
            continue

        # Count the occurrence of each noun
        noun_counts = Counter(nouns)

        # Select the most common noun as the subject of the question
        if noun_counts:
            subject = noun_counts.most_common(1)[0][0]

            # Generate the question stem
            question_stem = sentence.replace(subject, "_______")

            # Generate answer choices
            answer_choices = [subject]

            # Add some random words from the text as distractors
            for _ in range(3):
                distractor = random.choice(list(set(nouns) - set([subject])))
                answer_choices.append(distractor)

            # Shuffle the answer choices
            random.shuffle(answer_choices)

            # Append the generated MCQ to the list
            correct_answer = chr(64 + answer_choices.index(subject) + 1)  # Convert index to letter
            mcqs.append((question_stem, answer_choices, correct_answer))

    return mcqs

# Test the function with the provided text
text = """
The Greek historian knew what he was talking about. The Nile River fed Egyptian civilization for hundreds of years. The Longest River the Nile is 4,160 miles long—the world’s longest river. It begins near the equator in Africa and flows north to the Mediterranean Sea. In the south the Nile churns with cataracts. A cataract is a waterfall. Near the sea the Nile branches into a delta. A delta is an area near a river’s mouth where the water deposits fine soil called silt. In the delta, the Nile divides into many streams. The river is called the upper Nile in the south and the lower Nile in the north. For centuries, heavy rains in Ethiopia caused the Nile to flood every summer. The floods deposited rich soil along the Nile’s shores. This soil was fertile, which means it was good for growing crops. Unlike the Tigris and Euphrates, the Nile River flooded at the same time every year, so farmers could predict when to plant their crops.
"""

results = generate_mcqs(text, num_questions=10)


for i, mcq in enumerate(results,start=1):
    question_stem, answer_choices, correct_answer = mcq

    print(f"Q{i}: {question_stem}")
    for j, choice  in enumerate(answer_choices, start=1):
        print(f"{chr(64+j)}: {choice}")
    print(f"Correct Answer: {correct_answer}")

text = """
Artificial intelligence (AI) is revolutionizing various industries by enabling machines to perform tasks that typically require human intelligence. One area where AI is making significant strides is in natural language processing (NLP), allowing computers to understand and generate human language. NLP applications range from virtual assistants like Siri and Alexa to sentiment analysis in social media.

Another emerging technology is blockchain, a decentralized digital ledger that securely records transactions across a network of computers. Blockchain is best known as the technology behind cryptocurrencies like Bitcoin, but its potential extends far beyond digital currencies. It has applications in supply chain management, healthcare, and voting systems, among others.

The Internet of Things (IoT) refers to the network of interconnected devices embedded with sensors, software, and other technologies, enabling them to collect and exchange data. IoT devices can include everyday objects like smart thermostats, wearable fitness trackers, and industrial machinery. The data generated by IoT devices can be analyzed to improve efficiency, monitor performance, and enhance user experience.

Virtual reality (VR) and augmented reality (AR) are immersive technologies that blend the physical and digital worlds. VR creates a fully immersive simulated environment, while AR overlays digital content onto the real world. These technologies have applications in gaming, education, healthcare, and training, offering new ways to interact with digital content and experiences.

Cybersecurity is a critical concern in today's digital age, with cyberattacks becoming increasingly sophisticated and widespread. Organizations must employ robust security measures to protect their data, networks, and systems from unauthorized access, malware, and other cyber threats. This includes encryption, firewalls, intrusion detection systems, and regular security audits.

Quantum computing is an emerging field that leverages the principles of quantum mechanics to perform calculations at speeds far beyond traditional computers. Unlike classical bits, which can only exist in one state (0 or 1), quantum bits (qubits) can exist in multiple states simultaneously, allowing for parallel processing and exponential computational power. Quantum computing has the potential to revolutionize fields such as cryptography, optimization, and drug discovery.
"""

results = generate_mcqs(text, num_questions=10)


for i, mcq in enumerate(results,start=1):
    question_stem, answer_choices, correct_answer = mcq

    print(f"Q{i}: {question_stem}")
    print('_______------------------------')
    for j, choice  in enumerate(answer_choices, start=1):
        print(f"{chr(64+j)}: {choice}")
    print(f"Correct Answer: {correct_answer}")
    print("============================================================================")